FROM php:8.3-apache

RUN apt-get update && \
    docker-php-ext-install mysqli pdo pdo_mysql

# Use the default development configuration
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
COPY php-file_upload.ini $PHP_INI_DIR/conf.d/